version: "3"
services:

  # shared redis container is deployed in order to sync crashes and store statistics
  # per fuzzing container run
  redis:
    image: redis:alpine
    ports:
      - "6543:6543"

  # orhcestration server engine that spins up additional containers
  # to isolate parallelized fuzzing processes
  orchestrator:
    build: ./orchestrator
    priviledged: true
    ports:
      - "1234:1234"
    links:
      - redis
    volumes:
      - tests:/tests
    environment:
      - TESTBED:/tests


volumes:
  tests:
