version: "3"
services:

  # synchronize output reports with redis
  redis:
    image: redis:5.0.6
    ports:
      - "6543"

  # "master" engine that spins up additional containers
  # to isolate parallelized fuzzing processes
  orchestrator:
    build: ./orchestrator
    links:
      - redis




