version: "3"
services:

  # synchronize output reports with redis
  redis:
    image: redis:alpine
    ports:
      - "6543:6543"

  # master server engine that spins up additional containers
  # to isolate parallelized fuzzing processes
  orchestrator:
    build: ./orchestrator
    command: something build
    links:
      - redis
    volumes:
      - tests

  # containerized client application that interacts with testbed environment
  # and instantiate worker jobs
  client:
    build: ./fuzzbed-cli
    command: python3.6 setup.py install
    links:
      - orchestrator
    volumes:
      - tests
