version: "3"
services:

  # shared redis container is deployed in order to sync crashes and store statistics
  # per fuzzing container run
  redis:
    image: redis:alpine
    ports:
      - "6543:6543"

  # spins up a container to automatically built CLI application for interacting with orchestrator
  cli:
    build: ./fuzzbed-cli
    priviledged: false
    ports:
      - "8000:8000"
    volumes:
      - tests:/tests
    enviroment:
      - FUZZBED_SERVER=0.0.0.0:1234

  # orchestration server engine that spins up additional containers
  # to isolate parallelized fuzzing processes
  orchestrator:
    build: ./orchestrator
    priviledged: true
    ports:
      - "1234:1234"
    links:
      - redis
    volumes:
      - tests:/tests
    environment:
      - TESTBED=/tests
      - REDIS_QUEUE_URL=redis:6543


# describes the shared volumes that exist between containers
#   - tests: points to our locally defined $TESTBED environment, and will be shared across
#            all fuzzer container jobs
#   - logs:  points to a shared volume that stores and aggregates fuzzer outputs
volumes:
  tests:
  logs:
